# Generated by Django 3.0.4 on 2021-05-23 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='notes',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='movie',
            name='picture',
            field=models.URLField(default='https://via.placeholder.com/300x400?text=No+photo', max_length=900),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
